name: v2-hdmiusb-rpi4
on: workflow_dispatch


jobs:
  os:
    uses: haha1997jiang/os/.github/workflows/os.yml@master
    with:
      BOARD: rpi4
      PLATFORM: v2-hdmiusb
    secrets:
      DEPLOY_KEY: "${{secrets.DEPLOY_KEY}}"
